0:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 4
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  3:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 2
1:
  0:
    Event Flag: 0x1a6
    Event Palette:
      Colors: 000gnmdkhbcdhkidb06gih7d0de0ac189kvphpkdjgacb444000gnmdkh17ecfg6dg078h7d0de0ac1898de8bc7aa788444000gnmkvpchidjghpvbfmh7d0de0ac189dimcfhaddadd444000gnm9de8bc79a0v06feh7d0de0ac189dfjbdgabd889444000gnmdkhkkdjfhjndbchh7d0de0ac189dimcfhadd9a8444000gnmdkh0v0kkd0v0bbd0af0de0ac189dimcfhadd9a8444
      Event Flag: 0x0
      Flash Effect: 0
      Sprite Palette: 0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 4
2:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x800d
    Event Palette:
      Colors: 000uuqorldfbkofvv9elcvcdircilcifbvlbqf9lc7ga8666000uuqorleohcihvr6jlsv1bircilcifbvlbqf9lc7ga8666000uuqorleohogckf8b95vcdircilcifbvvpoojkkdghb668000uuqorldfbkofvv9elcvcdircilcifbvlbqf9lc7ga8666000uuqorlv99koidu0elcvcdircilcifbukfslhlcerng666000uuqorlkkdjjodu0kc7vcdircilcifbvrcqnbmf9hc9666
      Event Flag: 0x0
      Flash Effect: 0
      Sprite Palette: 5
    Flash Effect: 0
    Sprite Palette: 5
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 5
  3:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
3:
  0:
    Event Flag: 0x8047
    Event Palette:
      Colors: 000uuqoqjcdcumipsoehmv1bmnfcicce7uuqoojkkdghb666000uuqoqjcbifsogfleeuv1bmnfcicce7plbkg9ic6cb7666000uuqoqjgcaikgvqimbdv6bmnfcicce7slfofakc7ja6666000uuqoqjc8fb95und9jcv6bmnfcicce7mksihnedhaac666000uuqoqjbadvj8vhicbpr68mnfcicbc5vretp8oh4ie6666000uuqoqja9esq7vfpvdgkkumnfcicce7vq7vj8vdasb7666
      Event Flag: 0x0
      Flash Effect: 0
      Sprite Palette: 0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
4:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 2
    Sprite Palette: 0
5:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  3:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
6:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 6
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  3:
    Event Flag: 0x120
    Event Palette:
      Colors: 000oqmoqmqf9koiglkbfeabbdkecgbac8mkeigbcc8985333000nofehubek7bhjovbfi7bhdkecgbac8mndjkbfg9cd7333000oogbfgjfageaglkbfeabbdkecgbac8mndjkbfg9cd7333000oqmoqmnf8b95tm8bfebcbdkecgbac8tm8nf8q58m35333000000bfedke000000000000000000000000000000000000000000bfedkegeaglkbfeabb000000000mndjkbfg9cd7000
      Event Flag: 0x0
      Flash Effect: 0
      Sprite Palette: 4
    Flash Effect: 0
    Sprite Palette: 4
  4:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  5:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  6:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
7:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
8:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
9:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 6
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  3:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  4:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  5:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
10:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  3:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  4:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  5:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  6:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 4
  7:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
11:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  3:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  4:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  5:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  6:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  7:
    Event Flag: 0x8174
    Event Palette:
      Colors: 00046b04825b13513515846a23424935d23735813602511100046b04825b13503515846a23426c35d23743h34c33911100046b04825b13503515846a23426c35d23743h34c33911100046b04825b13513515846a23459g37e34735813602511100046b04825b13513515846a25625725d23935813602511100046b04825b13513515846a23436c25b137358136025111
      Event Flag: 0x0
      Flash Effect: 0
      Sprite Palette: 0
    Flash Effect: 0
    Sprite Palette: 0
12:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 4
  3:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  4:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  5:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  6:
    Event Flag: 0x205
    Event Palette:
      Colors: 00046b04825b13513515846a23424935d23735813602511100046b04825b13503515846a23426c35d23743h34c33911100046b04825b13503515846a23426c35d23743h34c33911100046b04825b13513515846a23459g37e34735813602511100046b04825b13513515846a25625725d23935813602511100046b04825b13513515846a23436c25b137358136025111
      Event Flag: 0x0
      Flash Effect: 0
      Sprite Palette: 4
    Flash Effect: 0
    Sprite Palette: 4
  7:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
13:
  0:
    Event Flag: 0x11f
    Event Palette:
      Colors: 000uuqoqjvvnlohkkdghb0v0rvugoo7gddnlekh7rkv1b000000jklfijfggkmja99b780v0efivrl9ab0v0pdbnbajaa0000000v00v0eechgfcaajjj0v0efibcg9ab0v00v07ln0v0000000cee0ni0bf09e0dgegi111efibcg9abacccccaaa88b000000lllefihhheegaac89acbeefiabg9abccccccaaa88b000000hhhdedkknbcbdedbbb0v0efibcg9ab0v00v09a9787000
      Event Flag: 0x0
      Flash Effect: 0
      Sprite Palette: 5
    Flash Effect: 0
    Sprite Palette: 5
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  3:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 4
14:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  3:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  4:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 5
  5:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 3
  6:
    Event Flag: 0x800d
    Event Palette:
      Colors: 000hr7vusppnolktqkkhckfagd7fi9nhaeb7vussroonk888000pqkvusppnolkjhbhmvmnnfgkmkfgd6id8uuuutsrnh888000kr9vusppnolk0vvkhckfagd7fosisu9i6vvunrvifm8880000vvuqeppnolknnl0vv0vv0vvtqnolhge9vussroonk8880000vvvusppnmlgljfkhckfamjfifbqmije9vussroonk8880000vvjhd0vvgfcba8fca0vv0vvsojpi9gd7vussroonk888
      Event Flag: 0x0
      Flash Effect: 0
      Sprite Palette: 0
    Flash Effect: 0
    Sprite Palette: 0
  7:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
15:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  3:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  4:
    Event Flag: 0x800d
    Event Palette:
      Colors: 0000vvvvttrnrmiurnpmjqi8jd9okbhb5lfbsnkqlglgd8880000vvtvvtrnsnlurnpmjqi80vv0vvvkjpecsnkqlglgd888000gn9vvttrnmmmurnpmjqi8jd9hqukuv9g6vvvpqqiih8880000vv0vvtrnvlj0vvpmjqi8jd9vroqlfgfbsnkqlglgd888000ekgvvttrnfiekpmpqntohlgegebvsltlcsnkqlglgd888000qqkvvstrnvposikvnbsi8ld9uuutqqrmmsnkqlglgd888
      Event Flag: 0x0
      Flash Effect: 0
      Sprite Palette: 0
    Flash Effect: 0
    Sprite Palette: 0
  5:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  6:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  7:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
16:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  3:
    Event Flag: 0x205
    Event Palette:
      Colors: 00046b04825b13513515846a23424935d23735813602511100046b04825b13503515846a23426c35d23743h34c33911100046b04825b13503515846a23426c35d23743h34c33911100046b04825b13513515846a23459g37e34735813602511100046b04825b13513515846a25625725d23935813602511100046b04825b13513515846a23436c25b137358136025111
      Event Flag: 0x0
      Flash Effect: 0
      Sprite Palette: 5
    Flash Effect: 0
    Sprite Palette: 5
17:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  3:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  4:
    Event Flag: 0x822b
    Event Palette:
      Colors: 00046b01314442313434345923432435734323435834911100079c0130vv423134343a7c0iv56b15i3340vv0vv0vv111000cf50131446221343434592340vtisu4c675g89h7691110000vv0vv1446221343434592347ad3574362343580vv1110000vv0131440vv13434345956a0vv3573430vv0vv0vv1110000vv0vv14425c13434356723477a55734423435865b111
      Event Flag: 0x0
      Flash Effect: 0
      Sprite Palette: 0
    Flash Effect: 0
    Sprite Palette: 0
  5:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 2
  6:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  7:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
18:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
19:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 2
  3:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  4:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 4
  5:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  6:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
20:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x822b
    Event Palette:
      Colors: 00034701312777b35578b45bcjh48b013002muugno7ac11100034701312777b35578b45bbcj87d0130027aa57724411100034701312777bb5478b45b957a8101300215602422511100034701312789cefs11212875307301300262546938c111000789013127991bbcg00500640b44ga00bj600300100111000789013127e60bbc78b45b547a908b749a075042011111
      Event Flag: 0x0
      Flash Effect: 0
      Sprite Palette: 0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  3:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  4:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  5:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  6:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  7:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
21:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  3:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  4:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
22:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 6
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  3:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  4:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
23:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  3:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
24:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  3:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  4:
    Event Flag: 0x822b
    Event Palette:
      Colors: 00046b01314442313434345923432435734323435834911100079c0130vv423134343a7c0iv56b15i3340vv0vv0vv111000cf50131446221343434592340vtisu4c675g89h7691110000vv0vv1446221343434592347ad3574362343580vv1110000vv0131440vv13434345956a0vv3573430vv0vv0vv1110000vv0vv14425c13434356723477a55734423435865b111
      Event Flag: 0x0
      Flash Effect: 0
      Sprite Palette: 0
    Flash Effect: 0
    Sprite Palette: 0
25:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 6
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  3:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  4:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 2
  5:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  6:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  7:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
26:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 5
  2:
    Event Flag: 0x0
    Flash Effect: 4
    Sprite Palette: 0
  3:
    Event Flag: 0x0
    Flash Effect: 1
    Sprite Palette: 0
  4:
    Event Flag: 0x0
    Flash Effect: 3
    Sprite Palette: 0
  5:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
27:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  3:
    Event Flag: 0x8046
    Event Palette:
      Colors: 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000b48223102405000vrquvvjqmeli8hd3c9dacaaa777000000b4f426102216002laaf9boalf6gdafa78dacaaa777000000b4f426102216002laaf9boalf6gdafa78dacaaa777000000000000000000000000000000000000000000000000000
      Event Flag: 0x0
      Flash Effect: 0
      Sprite Palette: 0
    Flash Effect: 5
    Sprite Palette: 0
  4:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
28:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 4
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  3:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  4:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  5:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
29:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  3:
    Event Flag: 0x0
    Flash Effect: 8
    Sprite Palette: 0
  4:
    Event Flag: 0x0
    Flash Effect: 7
    Sprite Palette: 0
  5:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
30:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
31:
  0:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  1:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  2:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  3:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  4:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  5:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  6:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0
  7:
    Event Flag: 0x0
    Flash Effect: 0
    Sprite Palette: 0